services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - database
    healthcheck:
      test: ["CMD", "/main", "--health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s


  database:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    env_file :
      - path : ./.env
    


volumes:
 postgres_data :
